"""purchase list update

Revision ID: 02878f6430e4
Revises: 63c757c5ad2f
Create Date: 2024-05-20 15:50:13.686082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02878f6430e4'
down_revision: Union[str, None] = '63c757c5ad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
