"""purchase list add

Revision ID: 63c757c5ad2f
Revises: 7ab49770a384
Create Date: 2024-05-20 15:46:58.823641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c757c5ad2f'
down_revision: Union[str, None] = '7ab49770a384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seller', sa.Column('sallary', sa.Integer(), nullable=False))
    op.add_column('seller', sa.Column('is_personal', sa.Boolean(), nullable=False))
    op.add_column('seller', sa.Column('phone', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'seller', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='unique')
    op.drop_column('seller', 'phone')
    op.drop_column('seller', 'is_personal')
    op.drop_column('seller', 'sallary')
    op.drop_table('purchase_list')
    # ### end Alembic commands ###
