"""add purchases, sellers, update product

Revision ID: 7ab49770a384
Revises: 56bced70819d
Create Date: 2024-05-20 10:36:17.506651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab49770a384'
down_revision: Union[str, None] = '56bced70819d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=127), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_name')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('cost', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cost')
    op.drop_table('purchase')
    op.drop_table('seller')
    # ### end Alembic commands ###
